version: '3.9'

services:
  gke_node_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app/
    # container_name: quantum-coasters
    ports:
      - 8080:8080
    command: "npm run dev"

volumes:
    gke_node_app:
