apiVersion: v1
kind: Secret
metadata:
  name: flaskappdockerhubsecret
type: kubernetes.io/dockerconfigjson
data:
  # Turn into base 64 encoded with echo -n 'example' | base64
  docker-server: ''
  docker-username: ''
  docker-password: ''
  docker-email: ''
