# openssl genrsa -out https.key 2048
# openssl req -new -x509 -key https.key -out https.cert -days 3650 -subj /CN=demo.example.com
# kubectl create secret generic https --from-file=https.key --from-file=https.cert

apiVersion: v1
kind: Secret
metadata:
  name: https
type: Opaque
data:
  # Turn into base 64 encoded with echo -n 'example' | base64
  https.cert: ''
  https.key: ''
