apiVersion: v1
kind: Service
metadata:
  name: flask-app-loadbalancer
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  # Prevent a network hop, by configuring service to redirect all external traffic only to pods running on the node that received the connection.
  externalTrafficPolicy: Local
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
