apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  # Want the storage to support a single client (performing both read and writes).
  accessModes:
    - ReadWriteOnce
  # Specifying an empty string as the storage class name ensures the PVC binds to a pre-provisioned PV instead of dynamically provisioning a new one.
  storageClassName: ""
