{{- if .Values.https.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: https
type: Opaque
data:
  # Turn into base 64 encoded with echo -n 'example' | base64
  https.key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAzty6hEpeqdInEgzV09YYNOBk9kyaysphA0kZSUX7CDsi0qzJ
        jTJS7a5msi7RTm3lwUPpNFU3p0oGjfI1+Yavp/c/qq8QS8rSaMGhekWSQ9rHVRNU
        yF7KoUpd64TJb09gbC+8hP4XK0p5j3PB7QXg6F2rfnKWwVthu9qzmpnBgnbxk+dr
        1xuS7hI1vB3YQVkjYTLZtxDD/dI9vkDUmF2m/XPQQSMZRrBgdWeoly4knpz7TsS2
        hJeMCCP1F+NZSPGjavotXO1SASimSCQbA0KEyv7IgNp5/EkrEpmR+DMDqsXe8nnE
        h1js3KbMXGU4hSDXMAVyE7oNfGjqLrZObvFE5wIDAQABAoIBAGaMhCZa2+ziEp5f
        II3AoAVujH6RYVdQ1qETVua9O4JMFqpMICrQHM5ZW+3PSdHQp0qVCQH5kPpsty0d
        Oua1f1UMPFK4MKLyLDbkbtG3tZfP2Gtzht9CJr+op0C/dkCpIArh61oewIukgvi7
        kRKYjHOFJCQuWFAIpj3DYLAuswCiZAjwhvdz+gPOeEz3yZlvJN+zTua7pC5/rLFa
        b8dDUEti1YoekdQHTxvEXIWhwNdhRqr+7yOVsOU16k6YnQJOXHmJXR9XNRSTHqYo
        YmIx9EkMk/KbExFIgzka10j/9PZAouVwD/d9xsoF6HMaVUA4gpqKjChykRCn2tSf
        Iv1gJxECgYEA8sBwKHfdeYc7cbyQQshPe0/y6DHJ0uwuXn8H14bylNumX61zPf8y
        Z+Vd3wILG0AzoE5cE662QrtBGCwbYmEdJQ29AO89j8urSawjmCJs/mlf7rhKlpOw
        TrlqZoxHNwwIg3crzr5Gb05OqCifi8WU0huj2vzIJa/T2GOY5vwu9TkCgYEA2ibd
        7VW/hI7W/ENRHIb4iiRVLJf0kbF4impCiZ5gISstnl2VtmXn/WBg9wYy7Q5uysF0
        NcsqRWyicXiM9RQCDBhfY7C7PGI6emBUYJj0LDkYy5dCYR3i2p4tbNbUV5EunAne
        yqn5N+jwNrog9wZWzW78x/V5gFSbuVNUYAuZKx8CgYEAyzfurPIrpqFfUkfZPQ8T
        +tdjMp77pmeyKcmOdw+x5Iw9K7u4zh3lxLRvcVH0mkuU7I6s5o1MZ3D7fZDvG9zQ
        2UQ3BaFCmC6YpoRFCAdJ13G/rcj6KDRbVIxEVrT4qUyZk/Uf52PC80tK7duUNR6j
        B4G8Goejxmj7oBtA1Z4ocYECgYA8+0BuZ9nxpDxUqDy0TMaNVzq4DIJBd+rKRonz
        DmKw4vENo/uF0VbYbWitpP33ZmFyLEHgB7r5TTTbo2dD2yP3XZjMtUqhxpOyQdtU
        ZW1cL1nPD6lunHwdwLnSAvu4vszYsaml3X3dMzBzG/S7GPqK0su22dftF7mwRKsB
        bjyS4QKBgQCvUjNgpznqRtPaQsfZjb5phoEy1g+0MEoy5qOtIxVS2rlK4lJpugKb
        A46YOvJgJMVq+rHK0iTtyxMohcGYVztr1DVsrPuun9F+SsxzcceVPkLDlIkIcpVM
        Oc2EDWX2e+M0xbzXgodFQ/0Vlz/OPsprp63JETF509XktT12eBAhbg==
        -----END RSA PRIVATE KEY-----
{{- end }}
