apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-api.fullname" . }}-lb
  labels:
    {{- include "flask-app-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.loadbalancer.type }}
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: {{ .Values.service.loadbalancer.port }}
      targetPort: {{ .Values.service.loadbalancer.targetPort }}
      protocol: TCP
    - name: https
      port: 443
      targetPort: {{ .Values.service.loadbalancer.targetPort }}
      protocol: TCP
  selector:
    app: flask-app
    {{- include "flask-app-api.selectorLabels" . | nindent 4 }}
