{{- if .Values.https.tls.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: Opaque
data:
  tls.key: |
    # RSA private key here
  tls.cert: |
    # RSA cert here
{{- end }}
