{{- if .Values.https.tls.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: Opaque
data:
  tls.key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA6sqVymhQxxm65gTWR6PBP/rWxxRo/UyQh4uHO89j+P3ynhCb
        +eKj+WPqwC1zBgGkLkbHz4ZOPrlBYpuSWdY7RT+yQVAHmTzOwxu+3gH8dWOkE5f6
        U6mxcmycNGVYa6mFvrTtN91L+BJuzoD4T1ROCIFALbZ3VbedQ0x9MZTQ6OGQ3qWU
        JceWGc1Ctfnw80HJHCbzqAHZPpoTO04QF+gIaRWAeTWnFfwNrM5A3vZ43ogh1Nt+
        xL2NpnJFL7GqzEqCzIJuQtupso+UZbAj+j1He4yvLSmUVlgM/WvLh/mcmK+iR1Ck
        TkSBymqxZO0nS62nsLmXb5/NHq/DHpYec0CWnQIDAQABAoIBAAjR/3qRHKe+IbVO
        bTZXwoTCyZrE+4S4gZ118miey+SotZqWiSWEDCDsTf9WNcH+AcrzQcJcC0hz8S7h
        JUhWsfdSA0JM3Vw2WpYdzrfMX02RprJNvUuzTkU8K0oUnJO+1JVrepXkrFvvZVZA
        phNk2WGcaWrONgF0WmYS04kvTAHTlQ5vGXi4Or5NO0xzpofYISCGxrGUMmxB40lM
        wTkOJcR59AGa2ESUsXyEnQks0NNj6d4vYwfmMdyTybdHU6g0QVv2NEA7sQtlY4G9
        cpuRvov6rN+b0/hrAPhVcG9YleSZzF3atlSIwzxdFPKHCucClo14SRWqVvv6oBpj
        x9IHgYECgYEA+6LRrB+DYbHqam0tjBVyiySYLm/I4dhO7RmCtQ+1eAwU6AeDuO2r
        hZ1GZyv7yMelzYLxU1rNDfhmoiSiY+12s0MfFpogJn8pzIwpCo33f58etQOGml8Q
        RL6gV/Ra789svfC7fwufV4mx+gXiM1+RXrDTjDPfoBDNVE8tx2p4me0CgYEA7tz7
        OIYxi0c9JDkaRvj72kkWpmeLhthujL3CxlwSPpHafQoKvi2fIj3lRXHnI7G8+TkJ
        cfyh6hNb4RzV/YJLOcg82PcjxqzNQFmIT5hS3sP4mTkpJ7EYo4FMuSl0Hz/Ux6z7
        cXPRfBKFa+wKmJ83yA7I3yaZOEBAbDWHTedemXECgYEAysrczypWZ1VK5Zo3Kr3e
        IeTMACB2dAwvD0WP4PtX8/dIofXsYgyoPnYRVvRLZfP/2y+77MEwoCGgFOwRMxcc
        ojtlwoFTh7LTrNUH/kmLPH6v8JF22NHj+oLmFfwHjVxM9oYblLd5IsMFe8liEqTi
        Mr2uvz7O6eCgmWF2M0/LAcECgYEAhEQ1kE0urhMali5QkLBatbr3IdoAdwDt5l1F
        t5VQPPmC5O5kmH6muc1QYa368db/73lX85iTCA0EOZlAHYrCoRJyLypa0y7o0RNC
        2eBdMyGNTTtLwMDeBdwZYgbEWHF+H7t32JDrlSqkWuhvzaeMuekF7htviKh7g+/4
        JnlR9uECgYAkqxMCkUiif8Q8F09AAuAe4s/QqEgwIVnHWWY8g+QuX/xEs4xKkHq8
        juY3dteVxIyY/UVOV1oEAfFDkc+SpNFAjSd4CMP+elIqY9N04jZR+tmUuHIZwRp5
        lYW80ERDg1gXSfPTSrgvn7uffzdvRW4DppkUrBC6hpLJdsurOD+KgQ==
        -----END RSA PRIVATE KEY-----
    tls.cert: |
        -----BEGIN CERTIFICATE-----
        MIICsjCCAZoCCQDwoKTvyDLhZTANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBk
        ZW1vLmV4YW1wbGUuY29tMB4XDTIxMDYxNjIzMzUxMVoXDTIyMDYxMTIzMzUxMVow
        GzEZMBcGA1UEAwwQZGVtby5leGFtcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
        ggEPADCCAQoCggEBAOrKlcpoUMcZuuYE1kejwT/61scUaP1MkIeLhzvPY/j98p4Q
        m/nio/lj6sAtcwYBpC5Gx8+GTj65QWKbklnWO0U/skFQB5k8zsMbvt4B/HVjpBOX
        +lOpsXJsnDRlWGuphb607TfdS/gSbs6A+E9UTgiBQC22d1W3nUNMfTGU0OjhkN6l
        lCXHlhnNQrX58PNByRwm86gB2T6aEztOEBfoCGkVgHk1pxX8DazOQN72eN6IIdTb
        fsS9jaZyRS+xqsxKgsyCbkLbqbKPlGWwI/o9R3uMry0plFZYDP1ry4f5nJivokdQ
        pE5EgcpqsWTtJ0utp7C5l2+fzR6vwx6WHnNAlp0CAwEAATANBgkqhkiG9w0BAQsF
        AAOCAQEAAy941DOVEn3UyE+Hf0dlN8wqqSqnD+Df2u77G+kODftUMv9RqCeEqzvM
        gCQy2FdlDyLMtO8DbZJPZ2SFrhn6Gk+goOSwRh9g11icpOQCRw24F5ljEjAVpEp9
        VcR7rsUNDt0Kb7LdgyNJdUEw1e2PnAEKD5dOQlK0mPztc/bOqOepDhxI8ofWaeB4
        gbIi7tz13o+yC7Y//GsBZPyMwcS8C+i4tkTXp7PM8vVj7r6pmM7ewuvzgPKHZXkn
        nED/yCmJlwseR9g5DVzmb3cp2enMSJNbCn0223D1E3rMFjGMS7KQjuJ/9CdbC02Q
        +QWuPLX9zfC2o6hWfJhQ9M+btXzvkA==
        -----END CERTIFICATE-----
{{- end }}
